# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to datetime.datetime.now(timezone.utc).astimezone() to select the timezone.
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the migration file
# when using the 2.0 templates
# Note that the length of the slug field is set to 40
# If you upgrade your alembic version, subsequently generated files will use the new length
# This value is represented with the migration files and cannot be changed after running the
# migration files have been generated
# migration_word_length = 40

# Whether to run the migrations in batch mode or not. This is generally
# needed if on Windows or with some databases (such as sqlite without proper
# driver support for multiple statements) but can be omitted otherwise.
sqlalchemy.batch_mode = true

# By default, revision files
# are written as revision -> downgrade -> revision.
# New files 'version_path_separator' to change this template into the new revision -> revision.
# (used when creating the very first revision file. When the revision_files
# are more than one, this new template is ignored.)
# version_path_separator = :

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

sqlalchemy.url = driver://user:password@localhost/dbname


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
